apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-dev
  labels:
    app: express-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: express-dev
    name: docker-desktop
  project: default
  source:
    path: ./k8s-resources/express/overlays/dev
    repoURL: https://github.com/justinbukstel/cd-five-mins-local.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
